apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: varodrig-poi-gateway-app-dev
  annotations:
    argocd/app-name: varodrig-poi-gateway-app-dev
    backstage.io/kubernetes-id: varodrig-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: varodrig
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=varodrig-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/varodrig-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/varodrig/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/varodrig/deployments/varodrig-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/varodrig-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/varodrig"
  system: workshop-system-varodrig
  providesApis:
    - gateway-api-varodrig
  consumesApis:
    - backend-api-varodrig
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-varodrig
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/varodrig"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-varodrig
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://varodrig-poi-gateway-app-varodrig.apps.rosa916.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rosa916-rvhvd/varodrig-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/varodrig"
  system: workshop-system-varodrig
  definition:
    $text: https://github.com/rosa916-rvhvd/varodrig-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
